config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "files#index"

  post "/files/upload", to: "files#upload"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_speech_api.rb
class GoogleSpeechAPI
  require "google/cloud/speech"
  include Singleton

  PROJECT_ID = "kakiokoshi-chan".freeze
  AUDIO_DIR  = Rails.root.join("tmp", "audio")

  def initialize
    @speech = Google::Cloud::Speech.new(project: PROJECT_ID)
  end

  def transcript
    audio_file_name = "#{AUDIO_DIR}/0101001.wav"
    audio = @speech.audio(audio_file_name,
                          encoding: :linear16,
                          sample_rate: 44100,
                          language: "ja")

    results = audio.recognize
    results.first.transcript
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  def index
  end

  def upload
    uploaded_file = fileupload_param[:file]
    output_path = Rails.root.join("tmp", "audio", uploaded_file.original_filename)

    File.open(output_path, "w+b") do |file|
      file.write(uploaded_file.read)
    end

    if File.exist?(output_path)
      flash[:success] = "【#{uploaded_file.original_filename}】をアップロードしました。"
      redirect_to root_path
    else
      flash[:warning] = "ファイルをアップロードできませんでした。"
      render :upload
    end
  end

  private

    def fileupload_param
      params.require(:fileupload).permit(:file)
    end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def index
  end

  def upload
    uploaded_file = fileupload_param[:file]
    output_path = Rails.root.join("tmp", "audio", uploaded_file.original_filename)

    File.open(output_path, "w+b") do |file|
      file.write(uploaded_file.read)
    end

    if File.exist?(output_path)
      flash[:success] = "【#{uploaded_file.original_filename}】をアップロードしました。"
      redirect_to root_path
    else
      flash[:warning] = "ファイルをアップロードできませんでした。"
      render :upload
    end
  end

  private

    def fileupload_param
      params.require(:fileupload).permit(:file)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/audios/index.html.slim
div
  p ファイルアップロード
  / multipart: true にしないと、 ファイル名しか送信できない
  = form_with url: audios_upload_path, method: :post, local: true, multipart: true do
    = file_field :fileupload, :file
    = submit_tag "アップロード", class: "btn btn-outline-primary"

app/views/files/index.html.slim
div
  p ファイルアップロード
  / multipart: true にしないと、 ファイル名しか送信できない
  = form_with url: files_upload_path, method: :post, local: true, multipart: true do
    = file_field :fileupload, :file
    = submit_tag "アップロード"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | KakiokoshiChan
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - flash.each do |key, value|
      = value
    = yield